name: CI Workflow für Modul 324

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run linter
        run: |
          echo "Running linter..."
          npm run lint || echo "Linting failed. Please check the output."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test || echo "Tests failed. Please check the output."

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Deployment
        run: |
          echo "Deployment started..."
          # Echtes Deployment kann hier noch eingebaut werden
          echo "Deployment successful"