name: CI Workflow für Modul 324

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          echo "Installing dependencies for linting..."
          npm install

      - name: Run linter
        run: |
          echo "Running linter..."
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          echo "Installing dependencies for testing..."
          npm install

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Simulate deployment
        run: |
          echo "Deployment successful"